### This Notebook contains all the fucntions in the Markov Shocks module. To use any of them, just copy the function you need into your own notebook

#### Translated from Eva Carceles-Poveda's MATLAB codes

In [1]:
import numpy as np

# needed for compact printing of numpy arrays
# use precision to set the number of decimal digits to display
# use suppress=True to show values in full decimals instead of using scientific notation
np.set_printoptions(suppress=True,precision=4,linewidth=np.inf)

In [2]:
# lnshock: generates a lognormal shock
def ln_shock(rho, sigmae, T = 200):
    """ Syntax: y=ln_shock(rho,sigmae,T)
    
    This function generates a T-dimensional lognormal shock with mean zero, 
    persistence rho and innovation standard deviation sigmae.
    """
    r = np.random.standard_normal((T+1,1))
    y = np.ones((T+1,1))
    for i in np.arange(2,T+1):
         y[i]=np.exp(rho * np.log(y[i-1]) + sigmae * r[i])
    return y

In [3]:
print(ln_shock(0.1, 0.001, 100))

[[1.    ]
 [1.    ]
 [0.9999]
 [0.9999]
 [0.9993]
 [0.9981]
 [1.0008]
 [1.0001]
 [1.0008]
 [0.9992]
 [0.9996]
 [1.0006]
 [1.    ]
 [0.9989]
 [1.0016]
 [1.0001]
 [0.9996]
 [1.0008]
 [0.9991]
 [0.9999]
 [1.0032]
 [1.0011]
 [1.0004]
 [0.999 ]
 [0.9995]
 [0.9998]
 [1.0001]
 [0.9992]
 [0.9998]
 [1.0007]
 [1.0003]
 [0.9979]
 [1.0011]
 [0.9992]
 [1.0007]
 [1.0007]
 [1.001 ]
 [0.9998]
 [0.9999]
 [1.0004]
 [0.9985]
 [0.999 ]
 [1.0003]
 [1.002 ]
 [1.001 ]
 [1.0004]
 [1.0012]
 [0.9992]
 [1.0002]
 [0.9994]
 [0.999 ]
 [1.0009]
 [1.0005]
 [0.9995]
 [0.9986]
 [1.0004]
 [1.    ]
 [0.9996]
 [1.0011]
 [1.0002]
 [1.    ]
 [0.9997]
 [1.0006]
 [1.001 ]
 [0.9992]
 [1.0005]
 [1.0009]
 [0.9994]
 [0.9999]
 [1.0013]
 [0.9999]
 [1.0007]
 [1.0001]
 [1.    ]
 [0.9984]
 [1.0019]
 [1.    ]
 [0.9986]
 [1.0006]
 [1.0008]
 [1.0014]
 [1.0007]
 [1.0006]
 [1.0006]
 [1.0015]
 [1.0002]
 [0.9999]
 [0.9988]
 [1.    ]
 [1.0015]
 [1.001 ]
 [1.0012]
 [0.9996]
 [1.0015]
 [1.0016]
 [1.    ]
 [1.0008]
 [1.0004]
 [1.0003]
 [0.9988]


In [4]:
print(ln_shock.__doc__)

 Syntax: y=ln_shock(rho,sigmae,T)
    
    This function generates a T-dimensional lognormal shock with mean zero, 
    persistence rho and innovation standard deviation sigmae.
    


In [5]:
# lnshockm: generates a lognormal shock
def ln_shock_m(mu, rho, sigmae, T = 200):
    """ Syntax: y=ln_shock_m(mu,rho,sigmae,T)
    
    This function generates a T-dimensional lognormal shock with mean mu,
    persistence rho and innovation standard deviation sigmae.
    """
    
    r = np.random.standard_normal((T+1,1))
    y = np.ones((T+1,1)) * np.exp(mu/(1-rho))
    for i in np.arange(2,T+1):
         y[i]=np.exp(mu + rho * np.log(y[i-1]) + sigmae * r[i])
    return y

In [6]:
print(ln_shock_m(-0.0631, 0.9, 0.05, 100))

[[0.5321]
 [0.5321]
 [0.4839]
 [0.5229]
 [0.5131]
 [0.5324]
 [0.5705]
 [0.4884]
 [0.5027]
 [0.5075]
 [0.5224]
 [0.5551]
 [0.5226]
 [0.4962]
 [0.4922]
 [0.4911]
 [0.518 ]
 [0.5104]
 [0.4805]
 [0.4837]
 [0.4887]
 [0.5137]
 [0.4873]
 [0.4793]
 [0.4981]
 [0.4846]
 [0.5014]
 [0.5342]
 [0.538 ]
 [0.5026]
 [0.5156]
 [0.516 ]
 [0.5253]
 [0.5042]
 [0.5133]
 [0.5017]
 [0.5597]
 [0.5635]
 [0.5985]
 [0.5842]
 [0.534 ]
 [0.5366]
 [0.5409]
 [0.5565]
 [0.5384]
 [0.6113]
 [0.5759]
 [0.5724]
 [0.5679]
 [0.53  ]
 [0.5099]
 [0.4804]
 [0.4529]
 [0.4697]
 [0.4934]
 [0.4929]
 [0.4965]
 [0.5204]
 [0.5117]
 [0.5338]
 [0.5329]
 [0.5189]
 [0.5042]
 [0.51  ]
 [0.567 ]
 [0.5399]
 [0.5669]
 [0.5327]
 [0.5107]
 [0.5417]
 [0.5236]
 [0.4649]
 [0.4558]
 [0.4609]
 [0.4781]
 [0.4857]
 [0.4859]
 [0.4947]
 [0.5366]
 [0.5338]
 [0.5521]
 [0.5222]
 [0.5531]
 [0.5857]
 [0.5909]
 [0.5901]
 [0.6165]
 [0.6243]
 [0.6264]
 [0.6176]
 [0.6337]
 [0.6281]
 [0.6106]
 [0.5395]
 [0.5448]
 [0.5589]
 [0.5222]
 [0.5401]
 [0.5146]
 [0.5657]


In [7]:
print(ln_shock_m.__doc__)

 Syntax: y=ln_shock_m(mu,rho,sigmae,T)
    
    This function generates a T-dimensional lognormal shock with mean mu,
    persistence rho and innovation standard deviation sigmae.
    


In [8]:
# markovchain: generates a Markov chain
def markov_chain(Trans, T = 100, s0 = 0, me = 1):
    """ Syntax: y=markov_chain(Trans,T,s0,me)
    
    This function generates a simulation from a Markov chain.
    Trans is the transition matrix, T is the number of periods 
    to be simulated, s0 is the initial state, with zero as default, 
    me is the method (two possibilities are included, with the first 
    as default), y is the shock realization.
    """
    
    Trans = Trans.astype(float) # convert transition matrix to float for precision
    
    # Checking the mistakes from the inputs
    
    num_rows, num_cols = Trans.shape
    
    # check that Trans and s0 are well defined
    if num_rows != num_cols:
        print('Transition matrix must be square')
        return "markov_chain function did not complete execution. Please fix and run again."
    # return
    
    for k in np.arange(0,num_rows):
        if not np.isclose(Trans[k,:].sum(), 1, rtol = 1e-4):
            print('Row', k, ' does not sum to one')
            print('Normalizing row', k)
            Trans[k,:] = Trans[k,:] / Trans[k,:].sum()
    
    print("Transition Matrix:\n", Trans)
    
    if s0 not in np.arange(0, num_rows):
        print('Initial state', s0, ' is out of range')
        print('Initial state defaulting to 0')
        s0=0
        
    if me not in np.arange(1,3):
        print("There are only method 1 and method 2")
        print("Method defaulting to method 1")
        me = 1

    #rng = np.random.default_rng(3108)
    #X = rng.random((T,1))
    # Creating the shock realizations
    X = np.random.random((T,1))
    y = np.full((T,1),s0)
    #print("y=",y)
    #y[0,0] = s0
    
    if me == 1:
        for i in np.arange(1, T):
            for j in np.arange(0, num_rows):
                if X[i-1] < Trans[y[i-1],0:j+1].sum():
                    break
                j = j + 1
            y[i,0] = j
        y = y.T 
    elif me == 2:
        s = np.zeros((num_rows,1))
        s[s0] = 1
        cum = np.matmul(Trans, np.triu(np.ones(Trans.shape)))
        state = np.zeros((num_rows, T))
        for k in np.arange(0,T):
            state[:,k] = s[:,0]
            ppi = np.concatenate((np.zeros((1,1)), np.matmul(s.T,cum)), axis = 1)
            s=((X[k]<=ppi[:, 1:num_rows+1])*(X[k]>ppi[:, 0:num_rows])).T

        y = np.matmul(np.arange(0, num_rows),state)
        y = np.reshape(y,(T,1)).T.astype('int')
        
    
    
    return y

In [9]:
transition_matrix = np.array([[1, 2], [2, 5]])
print(markov_chain(transition_matrix))

Row 0  does not sum to one
Normalizing row 0
Row 1  does not sum to one
Normalizing row 1
Transition Matrix:
 [[0.3333 0.6667]
 [0.2857 0.7143]]
[[0 0 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0]]


In [10]:
transition_matrix2 = np.array([[1, 2, 3], [2, 5, 6]])
print(markov_chain(transition_matrix2))

Transition matrix must be square
markov_chain function did not complete execution. Please fix and run again.


In [11]:
transition_matrix3 = np.array([[1, 4], [2, 5]])
print(markov_chain(transition_matrix3, 100, 3, 2))

Row 0  does not sum to one
Normalizing row 0
Row 1  does not sum to one
Normalizing row 1
Transition Matrix:
 [[0.2    0.8   ]
 [0.2857 0.7143]]
Initial state 3  is out of range
Initial state defaulting to 0
[[0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 1 1 0 1 1 1]]


In [12]:
pi = np.array([[0.8010, 0.1837, 0.0147, 0.0005, 0.0000, 0.0000, 0.0000],
    [0.1831, 0.5308, 0.2419, 0.0414, 0.0027, 0.0000, 0.0000],
    [0.0148, 0.2417, 0.4401, 0.2495, 0.0512, 0.0026, 0.0000],
    [0.0005, 0.0414, 0.2495, 0.4171, 0.2495, 0.0414, 0.0005],
    [0.0000, 0.0026, 0.0512, 0.2495, 0.4401, 0.2417, 0.0148],
    [0.0000, 0.0000, 0.0027, 0.0414, 0.2419, 0.5308, 0.1831],
    [0.0000, 0.0000, 0.0000, 0.0005, 0.0147, 0.1837, 0.8010]])

#np.random.seed(0)

print(markov_chain(pi, 115, 1, 2))

Transition Matrix:
 [[0.801  0.1837 0.0147 0.0005 0.     0.     0.    ]
 [0.1831 0.5308 0.2419 0.0414 0.0027 0.     0.    ]
 [0.0148 0.2417 0.4401 0.2495 0.0512 0.0026 0.    ]
 [0.0005 0.0414 0.2495 0.4171 0.2495 0.0414 0.0005]
 [0.     0.0026 0.0512 0.2495 0.4401 0.2417 0.0148]
 [0.     0.     0.0027 0.0414 0.2419 0.5308 0.1831]
 [0.     0.     0.     0.0005 0.0147 0.1837 0.801 ]]
[[1 2 3 3 1 1 2 4 2 3 3 4 3 3 3 5 5 6 6 5 6 6 6 6 4 5 4 3 4 3 4 3 3 4 4 4 4 3 4 3 5 4 2 2 2 3 2 2 3 4 3 3 3 1 1 1 1 1 2 1 0 0 0 0 1 2 4 5 3 3 3 4 4 2 3 3 2 2 4 3 3 3 3 4 5 5 5 5 5 5 4 5 6 6 6 4 4 4 4 4 4 3 2 2 3 3 4 2 3 4 3 3 3 4 5]]


In [13]:
print(markov_chain.__doc__)

 Syntax: y=markov_chain(Trans,T,s0,me)
    
    This function generates a simulation from a Markov chain.
    Trans is the transition matrix, T is the number of periods 
    to be simulated, s0 is the initial state, with zero as default, 
    me is the method (two possibilities are included, with the first 
    as default), y is the shock realization.
    


In [14]:
# ergodic: calculates the stationary distribution of a Markov chain
def ergodic(Trans, me = 1):
    """ Syntax: y=ergodic(Trans, me)
    
    This function calculates the stationary distribution of a 
    Markov chain. Trans is the transition matrix and me is the 
    method (three possibilities are included, with the first 
    as default), P is the distribution.
    """
    
    Trans = Trans.astype(float) # convert transition matrix to float for precision
    
    # Checking the mistakes from the inputs
    
    num_rows, num_cols = Trans.shape
    
    # check that Trans and s0 are well defined
    if num_rows != num_cols:
        print('Transition matrix must be square')
        return "ergodic function did not complete execution. Please fix and run again."
    # return
    
    for k in np.arange(0,num_rows):
        if not np.isclose(Trans[k,:].sum(), 1, rtol = 1e-4):
            print('Row', k, ' does not sum to one')
            print('Normalizing row', k)
            Trans[k,:] = Trans[k,:] / Trans[k,:].sum()
    
    print("Transition Matrix:\n", Trans)
        
    if me not in np.arange(1,4):
        print("There are only methods 1, 2, or 3")
        print("Method defaulting to method 1")
        me = 1

        
        
    va, vec = np.linalg.eig(Trans.T)
    va = np.diag(va)
    r1, r2 = (np.absolute(va-1)<1e-14).nonzero()
    
    if r1.size == 1:
        if me == 1:
            M = np.identity(num_rows) - Trans.T
            one = np.ones((1,num_rows))
            MM = np.concatenate((M[0:num_rows-1,:], one), axis = 0)
            V = np.concatenate((np.zeros((num_rows-1,1)), np.ones((1,1))), axis = 0)
            P = np.matmul(np.linalg.inv(MM), V)
            
        elif me == 2:
            trans = Trans.T
            p0 = (1/num_rows)*np.ones((num_rows,1))
            test = 1
            while test > 1e-5:
                p1 = np.matmul(trans, p0)
                test = np.absolute(p1-p0).max()
                p0 = p1
            P=p0
            
        elif me == 3:
            P = np.linalg.matrix_power(Trans,1000000)
            P = P[1,:].T
            P = P[:, np.newaxis] # view P as a column vector
            
    else:
        print('Sorry, there is more than one distribution. All of them, subject to normalization if not')
        print('summing up to one, are the columns of the matrix corresponding to the unity eigenvalues in va') 
        P = vec
        print("va =", va)
    
    
    return P

In [15]:
trans=np.array([[0.8, 0.1, 0.1], [0, 0.2, 0.8], [0.7, 0.3, 0]])
va, vec = np.linalg.eig(trans.T)
va = np.diag(va)
r1, r2 = (np.absolute(va-1)<1e-014).nonzero()
print("r1 =", r1, "r2 =", r2)
print(r1.size)
print(np.absolute(va-1)<1e-014)
print(vec)
print(va)

r1 = [0] r2 = [0]
1
[[ True False False]
 [False False False]
 [False False False]]
[[ 0.9384  0.8122 -0.4788]
 [ 0.2178 -0.3333 -0.3333]
 [ 0.2681 -0.4788  0.8122]]
[[ 1.      0.      0.    ]
 [ 0.      0.3873  0.    ]
 [ 0.      0.     -0.3873]]


In [16]:
trans=np.array([[0.8, 0.1, 0.1], [0, 0.2, 0.8], [0.7, 0.3, 0]])
print("Method 1:")
print("Stationary Distribution:\n", ergodic(trans,1))
print("Method 2:")
print("Stationary Distribution:\n", ergodic(trans,2))
print("Method 3:")
print("Stationary Distribution:\n", ergodic(trans,3))

Method 1:
Transition Matrix:
 [[0.8 0.1 0.1]
 [0.  0.2 0.8]
 [0.7 0.3 0. ]]
Stationary Distribution:
 [[0.6588]
 [0.1529]
 [0.1882]]
Method 2:
Transition Matrix:
 [[0.8 0.1 0.1]
 [0.  0.2 0.8]
 [0.7 0.3 0. ]]
Stationary Distribution:
 [[0.6588]
 [0.1529]
 [0.1882]]
Method 3:
Transition Matrix:
 [[0.8 0.1 0.1]
 [0.  0.2 0.8]
 [0.7 0.3 0. ]]
Stationary Distribution:
 [[0.6588]
 [0.1529]
 [0.1882]]


In [17]:
print(ergodic.__doc__)

 Syntax: y=ergodic(Trans, me)
    
    This function calculates the stationary distribution of a 
    Markov chain. Trans is the transition matrix and me is the 
    method (three possibilities are included, with the first 
    as default), P is the distribution.
    


In [18]:
# iid: generates an iid shock
def iid(prob, T = 100, me = 1):
    """ Syntax: y=iid(prob, T, me)
    
    This function generates a simulation from an iid random variable 
    prob is the probability vector, T is the number of periods to be 
    simulated (default is 100), me is the method (two possibilities 
    are included and it is the first by default), y is the shock realization.
    """
    
    if me not in np.arange(1,3):
        print("There are only method 1 and method 2")
        print("Method defaulting to method 1")
        me = 1
    
    # Checking the mistakes from the inputs
    if not np.isscalar(T):
        print("The number of realizations must be a scalar")
        return "iid function did not complete execution. Please fix and run again."
        
        
    # if the number of realizations in not an natural number, 
    # the following takes the abs. value and rounds to the nearest natural number.    
    T = np.around(np.absolute(T)) 

    # checking if prob is a vector or not
    if np.squeeze(prob).ndim != 1:
        print("prob must be a vector of probabilities")
        return "iid function did not complete execution. Please fix and run again."
    
    prob = np.absolute(prob)
    if not np.isclose(prob.sum(), 1, rtol = 1e-4):
        print('The probabilities do not sum to one. Will normalize probabilities.')
        prob = prob / prob.sum()
    
    print("Probability Matrix:\n", prob)
    
    X = np.random.random((T,1))
    m = prob.size
    y = np.zeros((T,1))

    if me == 1:
        for i in np.arange(0, T):
            for j in np.arange(0, m):
                if X[i] < prob[0:j].sum():
                    break
                j = j + 1
            y[i,0] = j 
        
    elif me == 2:
        P = prob.cumsum(axis = 0)  # creates a vector of cumulated probabilities
        for i in np.arange(0, T):
            j, k = (X[i] < P).nonzero()
            y[i,0] = j[0]+1
    
    
    return y

In [19]:
tt = ergodic(trans)
#print(tt)
print("Method 1:")
mm=iid(tt,100,1)
print((mm == 1).sum())
print((mm == 2).sum())
print((mm == 3).sum())

print("Method 2:")
mm=iid(tt,100,2)
print((mm == 1).sum())
print((mm == 2).sum())
print((mm == 3).sum())

Transition Matrix:
 [[0.8 0.1 0.1]
 [0.  0.2 0.8]
 [0.7 0.3 0. ]]
Method 1:
Probability Matrix:
 [[0.6588]
 [0.1529]
 [0.1882]]
74
12
14
Method 2:
Probability Matrix:
 [[0.6588]
 [0.1529]
 [0.1882]]
64
10
26


In [20]:
print(iid.__doc__)

 Syntax: y=iid(prob, T, me)
    
    This function generates a simulation from an iid random variable 
    prob is the probability vector, T is the number of periods to be 
    simulated (default is 100), me is the method (two possibilities 
    are included and it is the first by default), y is the shock realization.
    


In [21]:
# markovapprox: approximates a continuous AR(1) process with a Markov chain
# Eva Carceles-Poveda's version. You can use this function, Floden's tauchen function, or Sargent's tauchen function.

from scipy.stats import norm
def markov_approx(rho, sigma, m, N):
    """ Syntax: [Tran,s,p,arho,asigma]=markovapprox(rho,sigma,m,N)
    
    This function approximates a first-order autoregressive process 
    with persistence rho and innovation standard deviation sigma with 
    an N state Markov chain; m determines the width of the discretized 
    state space, Tauchen uses m=3, with ymax=m*vary,ymin=-m*vary, where 
    ymax and ymin are the two boundary points, Tran is the transition 
    matrix of the Markov chain, s is the discretized state space, p is 
    the chain stationary distribution, arho is the theoretical first 
    order autoregression coefficient for the Markov chain, asigma is 
    the theoretical standard deviation for the Markov chain.
    
    Translated from Eva Carceles-Poveda 2003 MATLAB code
    """
    
    # Discretize the state space
    stvy = np.sqrt(sigma**2/(1-rho**2))   # standard deviation of y(t)
    ymax = m*stvy                         # upper boundary of state space
    ymin = -ymax                          # lower boundary of state space
    w = (ymax-ymin)/(N-1)                 # distance between points
    s = w * np.arange(ymin/w, ymax/w+1)   # the discretized state space        

    
    # Calculate the transition matrix
    Tran = np.zeros((N,N))
    for j in np.arange(0,N):
        for k in np.arange(1,N-1):
            Tran[j,k] = norm.cdf(s[k]-rho*s[j]+w/2,0,sigma) - norm.cdf(s[k]-rho*s[j]-w/2,0,sigma);
            
        Tran[j,0] = norm.cdf(s[0]-rho*s[j]+w/2,0,sigma);
        Tran[j,N-1] = 1 - norm.cdf(s[N-1]-rho*s[j]-w/2,0,sigma);
        
    # Check that Tran is well specified
    if not np.all(np.isclose(np.sum(Tran.T, axis=0), np.squeeze(np.ones((1,N))))):
        # find rows not adding up to one
        str = (np.absolute(np.sum(Tran.T, axis=0))-np.squeeze(np.ones((1,N)))<1e-14).nonzero()          
        print('error in transition matrix')
        print('rows', str[0],' do not sum to one')
    
    
    # Calculate the invariant distribution of Markov chain
    Trans = Tran.T
    p = (1/N)*np.ones((N,1)) # initial distribution of states
    test = 1;
    while test > 1e-8:
        p1 = np.matmul(Trans,p)
        test=np.max(np.abs(p1-p))
        p = p1
    
    
    meanm = np.matmul(s,p)            # mean of invariant distribution of chain
    varm = np.matmul((s-meanm)**2,p)  #variance of invariant distribution of chain  
    midaut1 = np.matmul((s-meanm)[:, np.newaxis],(s-meanm)[np.newaxis, :]) # cross product of deviation from mean of yt and yt-1                    
    probmat = np.matmul(p,np.ones((1,N)))     # each column is invariant distribution   
    midaut2 = Tran*probmat*midaut1 # product of the first two terms is joint distribution of (Yt-1,Yt)                                    
    autcov1 = np.sum(midaut2)    #  first-order auto-covariance
    
#     print("meanm",meanm)
#     print("varm",varm)
#     print("midaut1",np.round(midaut1,4))
#     print("probmat",np.round(probmat,4))
#     print("midaut2",np.round(midaut2,4))
#     print("autcov1",autcov1)
    
    arho = autcov1/varm           # theoretical first order autoregression coefficient
    asigma = np.sqrt(varm)           # theoretical standard deviation
    
    return Tran, s, p, arho, asigma

In [22]:
rho=0.95
sigmae=0.01
N=7
m=3

Pi, teta, P, arho, asigma = markov_approx(rho,sigmae,m,N)
print("Transition Matrix:\n", Pi)
print("Discretized State Space:\n", teta)
print("The chain stationary distribution:\n", P)
print("Theoretical first order autoregression coefficient:\n", arho)
print("Theoretical standard deviation:\n", asigma)

Transition Matrix:
 [[0.8688 0.1312 0.     0.     0.     0.     0.    ]
 [0.0273 0.8726 0.1001 0.     0.     0.     0.    ]
 [0.     0.0391 0.8861 0.0748 0.     0.     0.    ]
 [0.     0.     0.0547 0.8907 0.0547 0.     0.    ]
 [0.     0.     0.     0.0748 0.8861 0.0391 0.    ]
 [0.     0.     0.     0.     0.1001 0.8726 0.0273]
 [0.     0.     0.     0.     0.     0.1312 0.8688]]
Discretized State Space:
 [-0.0961 -0.0641 -0.032   0.      0.032   0.0641  0.0961]
The chain stationary distribution:
 [[0.0189]
 [0.0906]
 [0.2319]
 [0.3173]
 [0.2319]
 [0.0906]
 [0.0189]]
Theoretical first order autoregression coefficient:
 [0.9622]
Theoretical standard deviation:
 [0.0396]


In [23]:
print(markov_approx.__doc__)

 Syntax: [Tran,s,p,arho,asigma]=markovapprox(rho,sigma,m,N)
    
    This function approximates a first-order autoregressive process 
    with persistence rho and innovation standard deviation sigma with 
    an N state Markov chain; m determines the width of the discretized 
    state space, Tauchen uses m=3, with ymax=m*vary,ymin=-m*vary, where 
    ymax and ymin are the two boundary points, Tran is the transition 
    matrix of the Markov chain, s is the discretized state space, p is 
    the chain stationary distribution, arho is the theoretical first 
    order autoregression coefficient for the Markov chain, asigma is 
    the theoretical standard deviation for the Markov chain.
    
    Translated from Eva Carceles-Poveda 2003 MATLAB code
    
